
DROP TABLE IF EXISTS mdl_load_user;
CREATE TABLE IF NOT EXISTS `ACEA`.`mdl_load_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` CHAR(10) NOT NULL,
  `status` CHAR(3) NULL DEFAULT 'NEW',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone1` VARCHAR(20) NOT NULL,
  `phone_mvola` VARCHAR(20) NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `matricule` VARCHAR(45) NOT NULL,
  `autre_prenom` VARCHAR(50) NULL,
  `genre` CHAR(1) NULL,
  `datedenaissance` DATE NULL,
  `lieu_de_naissance` VARCHAR(50) NULL,
  `situation_matrimoniale` VARCHAR(20) NULL,
  `compte_fb` VARCHAR(200) NULL,
  `etablissement_origine` VARCHAR(200) NULL,
  `serie_bac` VARCHAR(150) NULL,
  `annee_bac` SMALLINT NULL,
  `numero_cin` VARCHAR(50) NULL,
  `date_cin` DATE NULL,
  `lieu_cin` VARCHAR(50) NULL,
  `nom_pnom_par1` VARCHAR(250) NULL,
  `email_par1` VARCHAR(50) NULL,
  `phone_par1` VARCHAR(20) NULL,
  `profession_par1` VARCHAR(200) NULL,
  `adresse_par1` VARCHAR(200) NULL,
  `city_par1` VARCHAR(50) NULL,
  `nom_pnom_par2` VARCHAR(250) NULL,
  `phone_par2` VARCHAR(20) NULL,
  `profession_par2` VARCHAR(200) NULL,
  `centres_interets` VARCHAR(500) NULL,
  `cohorte_mention` VARCHAR(50) NOT NULL,
  `cohorte_niveau` VARCHAR(50) NOT NULL,
  `cohorte_parcours` VARCHAR(50) NULL,
  `cohorte_groupe` VARCHAR(20) NULL,
  `core_cohort_id` TINYINT NULL,
  `gsheet_id` BIGINT NOT NULL,
  `flow_id` BIGINT NULL,
  `core_status_matrimonial` CHAR(1) NULL,
  PRIMARY KEY (`id`));

-- cohort id must be in uac_showuser;
DROP TABLE IF EXISTS mdl_userx;
CREATE TABLE IF NOT EXISTS `ACEA`.`mdl_userx` (
  `id` BIGINT UNSIGNED NOT NULL,
  `username` CHAR(10) NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone1` VARCHAR(20) NOT NULL,
  `phone_mvola` VARCHAR(20) NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `matricule` VARCHAR(45) NOT NULL,
  `autre_prenom` VARCHAR(50) NULL,
  `genre` CHAR(1) NOT NULL,
  `datedenaissance` DATE NOT NULL,
  `lieu_de_naissance` VARCHAR(50) NULL,
  `situation_matrimoniale` CHAR(1) NULL,
  `compte_fb` VARCHAR(200) NULL,
  `etablissement_origine` VARCHAR(200) NULL,
  `serie_bac` VARCHAR(150) NULL,
  `annee_bac` SMALLINT NULL,
  `numero_cin` VARCHAR(50) NULL,
  `date_cin` DATE NULL,
  `lieu_cin` VARCHAR(50) NULL,
  `nom_pnom_par1` VARCHAR(250) NULL,
  `email_par1` VARCHAR(50) NULL,
  `phone_par1` VARCHAR(20) NULL,
  `profession_par1` VARCHAR(200) NULL,
  `adresse_par1` VARCHAR(250) NULL,
  `city_par1` VARCHAR(50) NULL,
  `nom_pnom_par2` VARCHAR(250) NULL,
  `phone_par2` VARCHAR(20) NULL,
  `profession_par2` VARCHAR(200) NULL,
  `centres_interets` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username_UNIQUE` (`username`),
  UNIQUE KEY `email_UNIQUE` (`email`));
