controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

main:
    path:       /
    controller: App\Controller\HomeController::index
universite:
    path:       /universite
    controller: App\Controller\StaticController::universite
cgu:
    path:       /cgu
    controller: App\Controller\StaticController::cgu
reglassiduite:
    path:       /reglassiduite
    controller: App\Controller\StaticController::reglassiduite
reglementinterieur:
    path:       /reglementinterieur
    controller: App\Controller\StaticController::reglementinterieur
contact:
    path:       /contact
    controller: App\Controller\StaticController::contact
mention:
    path:       /mention
    controller: App\Controller\StaticController::mention
news:
    path:       /news
    controller: App\Controller\StaticController::news
partner:
    path:       /partner
    controller: App\Controller\StaticController::partner
calendar:
    path:       /calendar
    controller: App\Controller\StaticController::calendar
letsgetitstarted:
    path:       /letsgetitstarted
    controller: App\Controller\TutorialController::letsgetitstarted
helpfraisdescolarite:
    path:       /helpfraisdescolarite
    controller: App\Controller\TutorialController::helpfraisdescolarite
concours:
    path:       /concours
    controller: App\Controller\TutorialController::concours
resultatconcours:
    path:       /resultatconcours
    controller: App\Controller\StaticController::resultatconcours
login:
    path:       /uaclogin
    controller: App\Controller\ConnectionController::login
logout:
    path:       /uaclogout
    controller: App\Controller\ConnectionController::logout
verify_connection:
    path:       /verify-connection
    controller: App\Controller\ConnectionController::verify
profile:
    path:       /profile/{page}/{week}
    controller: App\Controller\ProfileController::show
    defaults:
        page:   0
        week:   0
cartezp:
    path:       /cartezp/{page}
    controller: App\Controller\CartezpController::show
    defaults:
        page:   0
scan:
    path:       /scan/{rule}
    controller: App\Controller\ScanController::scan
loadscan:
    path:       /loadscan
    controller: App\Controller\ScanController::loadscan
servmail:
    path:       /servmail/{key}
    controller: App\Controller\ServmailController::send
    defaults:
        key:   0
loadedt:
    path:       /loadedt
    controller: App\Controller\AdminEDTController::loadedt
checkandloadedt:
    path:       /checkandloadedt
    controller: App\Controller\AdminEDTController::checkandloadedt
validateedt:
    path:       /validateedt/{master_id}
    controller: App\Controller\AdminEDTController::validateedt
    defaults:
        master_id:   0
showedt:
    path:       /showedt/{master_id}
    controller: App\Controller\AdminEDTController::showedt
    defaults:
        master_id:   0
jqcreateedt:
    path:       /jqcreateedt
    controller: App\Controller\AdminEDTController::jqcreateedt
jqPostEDTDB:
    path:       /jqPostEDTDB
    controller: App\Controller\AdminEDTController::jqPostEDTDB
manageredt:
    path:       /manageredt
    controller: App\Controller\AdminEDTController::manageredt
publishAllS1:
    path:       /publishAllS1
    controller: App\Controller\AdminEDTController::publishAllS1
dashboardass:
    path:       /dashboardass
    controller: App\Controller\AdminEDTController::dashboardass
managerstu:
    path:       /managerstu
    controller: App\Controller\AdminSTUController::managerstu
checklastscan:
    path:       /checklastscan
    controller: App\Controller\AdminSTUController::checklastscan
didiapply:
    path:       /didiapply
    controller: App\Controller\ProfileController::didiapply
verify_application:
    path:       /verify-application
    controller: App\Controller\ProfileController::verifyapplication
vieetudiante:
    path:       /vieetudiante
    controller: App\Controller\StaticController::vieetudiante
provinceint:
    path:       /provinceint
    controller: App\Controller\StaticController::provinceint
visit:
    path:       /visit
    controller: App\Controller\StaticController::visit
verifdiplomatxt:
    path:       /verifdiplomatxt
    controller: App\Controller\StaticController::verifdiplomatxt
gotoalledt:
    path:       /gotoalledt/{week_id}
    controller: App\Controller\StaticController::gotoalledt
    defaults:
        week_id:   0
alumni:
    path:       /alumni
    controller: App\Controller\AdminAlumniController::main
refpay:
    path:       /refpay
    controller: App\Controller\AdminPayController::refpay
addpay:
    path:       /addpay
    controller: App\Controller\AdminPayController::addpay
loadmvo:
    path:       /loadmvo
    controller: App\Controller\AdminPayController::loadmvo
getpaymentforuserDB:
    path:       /getpaymentforuserDB
    controller: App\Controller\AdminPayController::getpaymentforuserDB
generatefaciliteDB:
    path:       /generatefaciliteDB
    controller: App\Controller\AdminPayController::generatefaciliteDB
generateValidateRedDB:
    path:       /generateValidateRedDB
    controller: App\Controller\AdminPayController::generateValidateRedDB
generateDeleteRedDB:
    path:       /generateDeleteRedDB
    controller: App\Controller\AdminPayController::generateDeleteRedDB
generatepaymentDB:
    path:       /generatepaymentDB
    controller: App\Controller\AdminPayController::generatepaymentDB
generateattribuerMvoDB:
    path:       /generateattribuerMvoDB
    controller: App\Controller\AdminPayController::generateattribuerMvoDB
getPaymentDetailsDB:
    path:       /getPaymentDetailsDB
    controller: App\Controller\AdminPayController::getPaymentDetailsDB
generateCancelPaymentDB:
    path:       /generateCancelPaymentDB
    controller: App\Controller\AdminPayController::generateCancelPaymentDB
generateCertificatScoDB:
    path:       /generateCertificatScoDB
    controller: App\Controller\AdminPayController::generateCertificatScoDB
generateOpeMultiDB:
    path:       /generateOpeMultiDB
    controller: App\Controller\AdminPayController::generateOpeMultiDB
checkandloadmvo:
    path:       /checkandloadmvo
    controller: App\Controller\AdminPayController::checkandloadmvo
managermvo:
    path:       /managermvo
    controller: App\Controller\AdminPayController::managermvo
managerpay:
    path:       /managerpay
    controller: App\Controller\AdminPayController::managerpay
managerjust:
    path:       /managerjust
    controller: App\Controller\AdminPayController::managerjust
dashboardpay:
    path:       /dashboardpay
    controller: App\Controller\AdminPayController::dashboardpay
addgradetoexam:
    path:       /addgradetoexam
    controller: App\Controller\AdminGradeController::addgradetoexam
loadgrascan:
    path:       /loadgrascan
    controller: App\Controller\AdminGradeController::loadgrascan
checkandloadgra:
    path:       /checkandloadgra
    controller: App\Controller\AdminGradeController::checkandloadgra
managergraexam:
    path:       /managergraexam
    controller: App\Controller\AdminGradeController::managergraexam
cancelexam:
    path:       /cancelexam
    controller: App\Controller\AdminGradeController::cancelexam
confirmcancelexam:
    path:       /confirmcancelexam
    controller: App\Controller\AdminGradeController::managergraexam
generategradetoexamDB:
    path:       /generategradetoexamDB
    controller: App\Controller\AdminGradeController::generategradetoexamDB
createreviewgrades:
    path:       /createreviewgrades
    controller: App\Controller\AdminGradeController::managergraexam
generatereviewexamDB:
    path:       /generatereviewexamDB
    controller: App\Controller\AdminGradeController::generatereviewexamDB
generateNewSubjectDB:
    path:       /generateNewSubjectDB
    controller: App\Controller\AdminGradeController::generateNewSubjectDB
generateDeleteSubjectDB:
    path:       /generateDeleteSubjectDB
    controller: App\Controller\AdminGradeController::generateDeleteSubjectDB
readonlyexam:
    path:       /readonlyexam
    controller: App\Controller\AdminGradeController::readonlyexam
managerprimitif:
    path:       /managerprimitif
    controller: App\Controller\AdminGradeController::managerprimitif
primitifline:
    path:       /primitifline
    controller: App\Controller\AdminGradeController::primitifline
missingstudent:
    path:       /missingstudent
    controller: App\Controller\AdminGradeController::missingstudent
diploma:
    path:       /diploma/{page}
    controller: App\Controller\DiplomaController::show
managerdiploma:
    path:       /managerdiploma
    controller: App\Controller\DiplomaController::managerdiploma
dematdiploma:
    path:       /dematdiploma/{page}
    controller: App\Controller\DiplomaController::dematdiploma
generateProfileModifyDB:
    path:       /generateProfileModifyDB
    controller: App\Controller\ProfileController::generateProfileModifyDB