controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

main:
    path:       /
    controller: App\Controller\HomeController::index
mention:
    path:       /mention
    controller: App\Controller\MentionController::index
profile:
    path:       /profile
    controller: App\Controller\ProfileController::show
login:
    path:       /login
    controller: App\Controller\ConnectionController::login
