controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

main:
    path:       /
    controller: App\Controller\HomeController::index
universite:
    path:       /universite
    controller: App\Controller\StaticController::universite
mentionslegales:
    path:       /mentionslegales
    controller: App\Controller\StaticController::mentionslegales
contact:
    path:       /contact
    controller: App\Controller\StaticController::contact
mention:
    path:       /mention
    controller: App\Controller\StaticController::mention
news:
    path:       /news
    controller: App\Controller\StaticController::news
partner:
    path:       /partner
    controller: App\Controller\StaticController::partner
tutoinscription:
    path:       /tutoinscription
    controller: App\Controller\TutorialController::tutoinscription
login:
    path:       /login
    controller: App\Controller\ConnectionController::login
logout:
    path:       /logout
    controller: App\Controller\ConnectionController::logout
verify_connection:
    path:       /verify-connection
    controller: App\Controller\ConnectionController::verify
profile:
    path:       /profile/{page}/{week}
    controller: App\Controller\ProfileController::show
    defaults:
        page:   0
        week:   0
cartezp:
    path:       /cartezp/{page}
    controller: App\Controller\CartezpController::show
    defaults:
        page:   0
scan:
    path:       /scan/{rule}
    controller: App\Controller\ScanController::scan
loadscan:
    path:       /loadscan
    controller: App\Controller\ScanController::loadscan
servmail:
    path:       /servmail/{key}
    controller: App\Controller\ServmailController::send
    defaults:
        key:   0
loadedt:
    path:       /loadedt
    controller: App\Controller\AdminEDTController::loadedt
checkandloadedt:
    path:       /checkandloadedt
    controller: App\Controller\AdminEDTController::checkandloadedt
validateedt:
    path:       /validateedt/{flow}
    controller: App\Controller\AdminEDTController::validateedt
    defaults:
        flow:   0
dashboardass:
    path:       /dashboardass
    controller: App\Controller\AdminEDTController::dashboardass
