controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

main:
    path:       /
    controller: App\Controller\HomeController::index
universite:
    path:       /universite
    controller: App\Controller\StaticController::universite
cgu:
    path:       /cgu
    controller: App\Controller\StaticController::cgu
reglassiduite:
    path:       /reglassiduite
    controller: App\Controller\StaticController::reglassiduite
reglementinterieur:
    path:       /reglementinterieur
    controller: App\Controller\StaticController::reglementinterieur
contact:
    path:       /contact
    controller: App\Controller\StaticController::contact
mention:
    path:       /mention
    controller: App\Controller\StaticController::mention
news:
    path:       /news
    controller: App\Controller\StaticController::news
partner:
    path:       /partner
    controller: App\Controller\StaticController::partner
letsgetitstarted:
    path:       /letsgetitstarted
    controller: App\Controller\TutorialController::letsgetitstarted
login:
    path:       /login
    controller: App\Controller\ConnectionController::login
logout:
    path:       /logout
    controller: App\Controller\ConnectionController::logout
verify_connection:
    path:       /verify-connection
    controller: App\Controller\ConnectionController::verify
profile:
    path:       /profile/{page}/{week}
    controller: App\Controller\ProfileController::show
    defaults:
        page:   0
        week:   0
cartezp:
    path:       /cartezp/{page}
    controller: App\Controller\CartezpController::show
    defaults:
        page:   0
scan:
    path:       /scan/{rule}
    controller: App\Controller\ScanController::scan
loadscan:
    path:       /loadscan
    controller: App\Controller\ScanController::loadscan
servmail:
    path:       /servmail/{key}
    controller: App\Controller\ServmailController::send
    defaults:
        key:   0
loadedt:
    path:       /loadedt
    controller: App\Controller\AdminEDTController::loadedt
checkandloadedt:
    path:       /checkandloadedt
    controller: App\Controller\AdminEDTController::checkandloadedt
validateedt:
    path:       /validateedt/{master_id}
    controller: App\Controller\AdminEDTController::validateedt
    defaults:
        master_id:   0
showedt:
    path:       /showedt/{master_id}
    controller: App\Controller\AdminEDTController::showedt
    defaults:
        master_id:   0

jqcreateedt:
    path:       /jqcreateedt
    controller: App\Controller\AdminEDTController::jqcreateedt
jqPostEDTDB:
    path:       /jqPostEDTDB
    controller: App\Controller\AdminEDTController::jqPostEDTDB

manageredt:
    path:       /manageredt
    controller: App\Controller\AdminEDTController::manageredt
dashboardass:
    path:       /dashboardass
    controller: App\Controller\AdminEDTController::dashboardass
managerstu:
    path:       /managerstu
    controller: App\Controller\AdminSTUController::managerstu
checklastscan:
    path:       /checklastscan
    controller: App\Controller\AdminSTUController::checklastscan
didiapply:
    path:       /didiapply
    controller: App\Controller\ProfileController::didiapply
verify_application:
    path:       /verify-application
    controller: App\Controller\ProfileController::verifyapplication
vieetudiante:
    path:       /vieetudiante
    controller: App\Controller\StaticController::vieetudiante
provinceint:
    path:       /provinceint
    controller: App\Controller\StaticController::provinceint
alumni:
    path:       /alumni
    controller: App\Controller\AdminAlumniController::main

refpay:
    path:       /refpay
    controller: App\Controller\AdminPayController::refpay
addpay:
    path:       /addpay
    controller: App\Controller\AdminPayController::addpay
addpaiddoc:
    path:       /addpaiddoc
    controller: App\Controller\AdminPayController::addpaiddoc
getpaymentforuserDB:
    path:       /getpaymentforuserDB
    controller: App\Controller\AdminPayController::getpaymentforuserDB
generatefaciliteDB:
    path:       /generatefaciliteDB
    controller: App\Controller\AdminPayController::generatefaciliteDB
