DELIMITER $$
DROP FUNCTION IF EXISTS fEscapeStr$$
CREATE FUNCTION fEscapeStr(
	input VARCHAR(1000)
)
RETURNS VARCHAR(1000)
DETERMINISTIC
BEGIN
	RETURN REPLACE(REPLACE(REPLACE(input, "'", " "), '"', ' '), ',', ' ');
END$$
