DELIMITER $$
DROP FUNCTION IF EXISTS fEscapeStr$$
CREATE FUNCTION fEscapeStr(
	input VARCHAR(1000)
)
RETURNS VARCHAR(1000)
DETERMINISTIC
BEGIN
	RETURN REPLACE(REPLACE(REPLACE(REPLACE(input, "'", " "), '"', ' '), ',', ' '), ';', '');
END$$

DELIMITER $$
DROP FUNCTION IF EXISTS fCapitalizeStr$$
CREATE FUNCTION fCapitalizeStr(
	input VARCHAR(1000)
)
RETURNS VARCHAR(1000)
DETERMINISTIC
BEGIN
	RETURN TRIM(CONCAT(UPPER(SUBSTRING(input,1,1)),LOWER(SUBSTRING(input,2))));
END$$
