USE ACEA;

PURGE BINARY LOGS BEFORE DATE_ADD(current_date, INTERVAL -10 DAY);

OPTIMIZE TABLE uac_load_edt;
OPTIMIZE TABLE uac_load_scan;
OPTIMIZE TABLE uac_scan;
OPTIMIZE TABLE uac_edt_master;
OPTIMIZE TABLE uac_edt_line;

FLUSH QUERY CACHE;

SELECT NOW() AS END_TIME;
